TrainingArgs:
    epochs: 1
    warmup_steps: 500
    batch_size: 1
    weight_decay: 0.01
    logging_steps: 10
    evaluation_strategy: steps
    eval_steps: 200
    save_steps: 10000
    gradient_accumulation_steps: 16